DATASET:
  name: 'hands'
  image_path: '/mnt/ssd2/BACKUP/Datasets/COCO2017/images'
  annotation_path: './data/hands/'
  inp_res: 256
  out_res: 64
  flip: True
  sigma: 1
  scale_factor: 0.25
  rot_factor: 30
  label_type: 'Gaussian' # Gaussian or Cauchy
MODEL:
  arch: 'hg'
  num_stacks: 2
  num_blocks: 1
  mobile: True
  skip_mode: 'sum' # sum or concat
  subset: null
TRAIN:
  num_workers: 4
  epochs: 90
  start_epoch: 0
  train_batch: 64
  test_batch: 64
  learning_rate: 0.0025
  momentum: 0
  weight_decay: 0
  schedule: [50, 65]
  gamma: 0.1
  sigma_decay: 0
MISC:
  checkpoint: '/mnt/hdd10tb/Users/hoangbm/checkpoint/pose-estimation/hourglass/'
  snapshot: 10
  resume: '/mnt/hdd10tb/Users/hoangbm/checkpoint/pose-estimation/hourglass/hands_hg_s2_mobile_all_sum/model_best.pth.tar'
  evaluate: False
  pck: 0.5
  out_onnx: '/home/hoangbm/hands.onnx'
